"""create video ratings

Revision ID: ed68c9ebdb33
Revises:
Create Date: 2026-08-15 20:09:40.537130

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed68c9ebdb33"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("original_title", sa.Text(), nullable=True),
        sa.Column("rating_number", sa.String(length=100), nullable=False),
        sa.Column("rating_date", sa.Date(), nullable=True),
        sa.Column("grade", sa.Text(), nullable=False),
        sa.Column("applicant_name", sa.Text(), nullable=False),
        sa.Column("producer_name", sa.Text(), nullable=True),
        sa.Column("production_country", sa.Text(), nullable=True),
        sa.Column("production_year", sa.Integer(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=True),
        sa.Column("running_time", sa.Text(), nullable=True),
        sa.Column("director_name", sa.Text(), nullable=True),
        sa.Column("lead_actor_name", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("core_harm_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rating_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_ratings")
    # ### end Alembic commands ###
